'use client'

// import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Provider } from 'react-redux'
import { store } from '@/store/store'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

const dancingScript = localFont({
  src: './fonts/DancingScript.woff',
  variable: '--font-dancing-script',
  weight: 'normal', // adjust if necessary
})

const billabong = localFont({
  src: './fonts/Billabong.woff',
  variable: '--font-billabong',
  weight: 'normal', // adjust if necessary
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dancingScript.variable} ${billabong.variable} antialiased`}
      >
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  )
}
